# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

clr_loglik_cpp <- function(beta, x, y, stratum, offset, total = TRUE) {
    .Call(`_clbart_clr_loglik_cpp`, beta, x, y, stratum, offset, total)
}

clr_grd_cpp <- function(beta, x, y, stratum, offset) {
    .Call(`_clbart_clr_grd_cpp`, beta, x, y, stratum, offset)
}

clr_fish_cpp <- function(beta, x, y, stratum, offset) {
    .Call(`_clbart_clr_fish_cpp`, beta, x, y, stratum, offset)
}

clr_cpp <- function(x, y, stratum, offset = NULL, start_values = NULL, max_iter = 100L, tol = 1e-7) {
    .Call(`_clbart_clr_cpp`, x, y, stratum, offset, start_values, max_iter, tol)
}

rlgam <- function(shape) {
    .Call(`_clbart_rlgam`, shape)
}

update_sigma <- function(r, sigma_scale, sigma_old) {
    .Call(`_clbart_update_sigma`, r, sigma_scale, sigma_old)
}

